#!/bin/bash

set -ex

if ! pgrep -q Spotify
then
    echo "Error: Spotify is not running"
    exit 1
fi

ARTIST=$(osascript -e 'tell application "Spotify" to artist of current track as string');
TRACK=$(osascript -e 'tell application "Spotify" to name of current track as string');

YOUTUBE="https://www.youtube.com"
LINK="$YOUTUBE/results?search_query="
URI=$(echo "$ARTIST-$TRACK, hd" | gsed -r 's/ /+/g')

SEARCH=$(curl -s "$LINK$URI" | grep -o 'href=\"/watch?v=.*\"' -m1 | cut -d'"' -f2)

open -a "/Applications/Google Chrome.app" "$YOUTUBE$SEARCH"
